"""empty message

Revision ID: ca1be236393e
Revises: b452b67ca959
Create Date: 2020-10-04 00:04:21.566503

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'ca1be236393e'
down_revision = 'b452b67ca959'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clients', sa.Column('date_of_birth', sa.DateTime(), nullable=True))
    op.drop_column('clients', 'data_nascimento')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clients', sa.Column('data_nascimento', mysql.DATETIME(), nullable=True))
    op.drop_column('clients', 'date_of_birth')
    # ### end Alembic commands ###
